name: tinyasync
description: >
  A minimal dart:async experiment.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/tinyasync

environment:
  sdk: ">=2.0.0-dev <2.0.0"

compiler:
  web:
    debug: dartdevc

dependencies:
  js: ^0.6.1

dev_dependencies:
  args: ^1.0.0
  kilobyte: ^0.1.0
  glob: ^1.1.5
  io:
    git: https://github.com/dart-lang/io
  node_preamble: ^1.4.0
  path: ^1.0.0
  test: ^0.12.0

transformers:
  - test/pub_serve:
      $include: test/**_test.dart
  - $dart2js:
      commandLineOptions:
          - --dump-info
          - --trust-type-annotations
          - --trust-primitives
