name: tinyasync
description: >
  A minimal dart:async experiment.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/tinyasync

environment:
  sdk: ">=2.0.0-dev <2.0.0"

compiler:
  web:
    debug: dartdevc

dependencies:
  js: ^0.6.1

dev_dependencies:
  kilobyte: ^0.1.0
  io: ^0.3.0
  node_preamble: ^1.4.0
  test: ^0.12.0

transformers:
  - test/pub_serve:
      $include: test/**_test.dart
  - $dart2js:
      commandLineOptions:
          - --trust-type-annotations
          - --trust-primitives
